![image.png](attachment:image.png)

In [1]:
import pandas as pd

## Series

In [ ]:
## Creating empty series
d=pd.Series(dtype='int32')

In [ ]:
d

Series([], dtype: int32)

In [ ]:
## Creating series with one element
d=pd.Series(17)

In [ ]:
d

0    17
dtype: int64

In [ ]:
## Creating series using tuple
t=(10,11,12)
d=pd.Series(t)

In [ ]:
d

0    10
1    11
2    12
dtype: int64

In [ ]:
##  creating series using list
d=pd.Series([45,78,56,445,78])

In [ ]:
d

0     45
1     78
2     56
3    445
4     78
dtype: int64

In [ ]:
## Creating series with array
import numpy as np
arr=np.array([1,2,3,4])
d=pd.Series(arr)

In [ ]:
d

0    1
1    2
2    3
3    4
dtype: int32

In [ ]:
## Using dictonary
d={'a':1,'b':2,'c':3,'d':4}

In [ ]:
b=pd.Series(d)

In [ ]:
b

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
arr_2=np.array([1,2,3])
s_2=pd.Series(arr_2,index=['one','two','three'])
s_2

one      1
two      2
three    3
dtype: int32

In [ ]:
## checking the datatype
type(s_2)

pandas.core.series.Series

In [ ]:
## access the data
d[3]

4

In [ ]:
b['a']

1

In [ ]:
s_2['one']

1

In [ ]:
## Slicing operation
d=pd.Series([1,2,3,5,47,98,7,8,6,32,78,2,8,289,258,78])

In [ ]:
d[0:9]

0     1
1     2
2     3
3     5
4    47
5    98
6     7
7     8
8     6
dtype: int64

In [ ]:
d[[4,5,3,6]] ## multiple index

4    47
5    98
3     5
6     7
dtype: int64

In [ ]:
arr3=np.array([1,2,4,6])
s=pd.Series(arr3,index=['one','Two','Three','Four'])   
s[0:9]

one      1
Two      2
Three    4
Four     6
dtype: int32

## DataFrame

In [ ]:
## empty dataframe
d=pd.DataFrame()

In [ ]:
print(d)

Empty DataFrame
Columns: []
Index: []

In [17]:
## using nested list
data=[[1,2,3,4],[14,12,1,'a',8],[7,8,9]]

In [18]:
d=pd.DataFrame(data)

In [19]:
d

    0   1  2     3    4
0   1   2  3     4  NaN
1  14  12  1     a  8.0
2   7   8  9  None  NaN

In [34]:
data=[['abc',1],['def',2],['ghi',3],['hij'],['klm','a']]

In [35]:
d=pd.DataFrame(data,columns=['A','B'])

In [36]:
d

     A     B
0  abc     1
1  def     2
2  ghi     3
3  hij  None
4  klm     a

In [20]:
## dataframe using dictonary
data={'name':['a','b','c','d','e','f'],'age':[45,12,48,25,12,56]}

In [21]:
d=pd.DataFrame(data)

In [22]:
d

  name  age
0    a   45
1    b   12
2    c   48
3    d   25
4    e   12
5    f   56

In [43]:
## Accessing the elements from dataframe
data=[['ALex',10,'Maths'],['Bob',12,'Science'],['Kelly',15,'Eco'],['Boris',14,'Geo'],['Ken',18,'English']]

In [44]:
d=pd.DataFrame(data,columns=['Name','Age','Subject'])

In [45]:
d

    Name  Age  Subject
0   ALex   10    Maths
1    Bob   12  Science
2  Kelly   15      Eco
3  Boris   14      Geo
4    Ken   18  English

In [46]:
## accessing one single column
d['Name']

0     ALex
1      Bob
2    Kelly
3    Boris
4      Ken
Name: Name, dtype: object

In [47]:
d.iloc[:,[0]]

    Name
0   ALex
1    Bob
2  Kelly
3  Boris
4    Ken

In [ ]:
## to acces the single element we use iloc it will always work with index
d.iloc[0,2] ## index of row ,columns

'Maths'

In [49]:
## loc will work on rows as well as names of columns
##d.loc[:,['Name']]
d.iloc[:,0]

0     ALex
1      Bob
2    Kelly
3    Boris
4      Ken
Name: Name, dtype: object

In [ ]:
d.loc[3] ## getting the rows

Name       Boris
Age           14
Subject      Geo
Name: 3, dtype: object

In [ ]:
d.iloc[:,[1,2]]

   Age  Subject
0   10    Maths
1   12  Science
2   15      Eco
3   14      Geo
4   18  English

In [50]:
d.iloc[:,1]

0    10
1    12
2    15
3    14
4    18
Name: Age, dtype: int64

In [ ]:
pwd

'C:\\Users\\user\\Downloads'